// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTZSDHZJWDcTd5jct_LE6Vb_EZ5BNtU_8',
    appId: '1:1039643665699:web:131316d10e6b3ad2a8d896',
    messagingSenderId: '1039643665699',
    projectId: 'moressang-cb29b',
    authDomain: 'moressang-cb29b.firebaseapp.com',
    storageBucket: 'moressang-cb29b.appspot.com',
    measurementId: 'G-DV1768S9PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf5aR9TnC0Rb_4s_EUZWYfCuuQnjLwnJs',
    appId: '1:1039643665699:android:2bb36b7249bb6253a8d896',
    messagingSenderId: '1039643665699',
    projectId: 'moressang-cb29b',
    storageBucket: 'moressang-cb29b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlIs7v6lWt38cWok39HsFoxhAMFKoDXk',
    appId: '1:1039643665699:ios:8089958b65531384a8d896',
    messagingSenderId: '1039643665699',
    projectId: 'moressang-cb29b',
    storageBucket: 'moressang-cb29b.appspot.com',
    iosClientId: '1039643665699-eebjrdr8b9qaib28m62qh2kkc9n5qv2d.apps.googleusercontent.com',
    iosBundleId: 'com.moressang.moressang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLlIs7v6lWt38cWok39HsFoxhAMFKoDXk',
    appId: '1:1039643665699:ios:8089958b65531384a8d896',
    messagingSenderId: '1039643665699',
    projectId: 'moressang-cb29b',
    storageBucket: 'moressang-cb29b.appspot.com',
    iosClientId: '1039643665699-eebjrdr8b9qaib28m62qh2kkc9n5qv2d.apps.googleusercontent.com',
    iosBundleId: 'com.moressang.moressang',
  );
}
